<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Kochedikov\Blog\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
$pagerBlock = $block->getChildBlock('post_pager');
$collection = $postVm->getPosts(3);
?>

<div class="blog-post-list">
    <h1><?= __('Blog posts'); ?></h1>
    <?php if (!$collection->count()): ?>
        <p> There are mo posts in this blog.</p>
    <?php else: ?>
        <ul>
            <?php foreach ($collection as $post): ?>
                <li>
                    <a href="<?= $block->getUrl('blog/post/detail', ['post_id'=> $post->getData('post_id')]); ?>">
                        <?= $escaper->escapeHtml($post->getData('title'));?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
        <?php if ($pagerBlock): ?>
            <?=  $postVm->getPager($collection, $pagerBlock); ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
